### ISSUE TITLE
Is there any example codes for the powershield?

### ISSUE THREAD

**Issue by candyriver** [simplefoc/Arduino-SimpleFOC-PowerShield#1]
I have get the board and fabricate it according to the tutorial, but I found the open_loop_velocity_control.ino  does not work. 
Is there any code for the powershield?

**Comment by askuric** [comment]
Hey @candyriver ,
I hope you've made it.

There are two things you can do:
Either enable the two additional INH pins in the Arduino setup function.
Or use the dev version of the library that has support for three enable pins. 

It will be documented and releasef very soon :)
