### ISSUE TITLE
Schematic missing

### ISSUE THREAD

**Issue by bikeNomad** [simplefoc/Arduino-SimpleFOC-PowerShield#4]
`/schematic.pdf` is not a schematic. Please add an actual schematic for those of us who don't want to fire up a Windows VM just to run the Altium viewer.

**Comment by askuric** [comment]
I am not sure that I follow. :slightly_smiling_face: 
 `schematic.pdf` is a pdf file with the schematic exported from Altium. But you do not need altium to view it. You can open it with any pdf viewer or even with most of web browsers.

**Comment by bikeNomad** [comment]
Sorry about that; I viewed the file in my web browser and the schematic page was blank. Downloading it revealed the schematic.
Thanks for your work!

**Comment by askuric** [comment]
No worries, I am glad you like it!
